Updated working drectory on step8

diff --git a/.github/workflows/documentation_accessibility_checks.yml b/.github/workflows/documentation_accessibility_checks.yml
--- a/.github/workflows/documentation_accessibility_checks.yml
+++ b/.github/workflows/documentation_accessibility_checks.yml
@@ -66,13 +66,20 @@ jobs:
 
        # Step 8: Run accessibility check 
       - name: Run accessibility check
-        working-directory: VAMobile/documentation
+        working-directory: ${{ github.workspace }} # Set the working directory to the repository's root directory
         run: |
-         while IFS= read -r url; do
+          # Ensure that the URLs file exists
+          if [ ! -f "urls.txt" ]; then
+            echo "Error: urls.txt file not found."
+            exit 1
+          fi
+          
+          while IFS= read -r url; do
            # Use a unique name for the report file based on the URL
            report_file="${url//\//-}-axe-report.json"
            axe "$url" --exit --tags wcag2a,wcag2aa > "$report_file"
-         done < urls.txt   
+          done < urls.txt   
+         
          
 
 
