CU/8737-rachael-detox-e2e-tests-refactor

diff --git a/.github/workflows/e2e_ios.yml b/.github/workflows/e2e_ios.yml
--- a/.github/workflows/e2e_ios.yml
+++ b/.github/workflows/e2e_ios.yml
@@ -73,6 +73,8 @@ jobs:
       - name: 'Get Matrix Value'
         id: matrix_value
         run: |
+          e2eNames=$(gh api department-of-veterans-affairs/va-mobile-app/VAMobile/e2e/tests --jq '.[].name')
+          echo "$e2eNames" 
           if [[ "${{ inputs.tests_to_run }}" == "" ]]; then
             echo "matrix=" >> "$GITHUB_OUTPUT"
             echo "empty_matrix=false" >> "$GITHUB_OUTPUT"
@@ -81,218 +83,218 @@ jobs:
             echo "empty_matrix=false" >> "$GITHUB_OUTPUT"
           fi
 
-  matrix-e2e-ios:
-    if: always() && needs.output_detox_tests_to_run.outputs.output1 != '' && needs.output_detox_tests_to_run.outputs.output2 != ''
-    runs-on: macos-14-xlarge
-    needs: output_detox_tests_to_run
-    env:
-      # Path to write secret key to. Also used by fastlane
-      APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
-      # Xcode project file name
-      IOS_PROJ_FILE: 'VAMobile.xcodeproj'
-      # Xcode scheme to build
-      IOS_SCHEME: 'VAMobileRelease'
+  # matrix-e2e-ios:
+  #   if: always() && needs.output_detox_tests_to_run.outputs.output1 != '' && needs.output_detox_tests_to_run.outputs.output2 != ''
+  #   runs-on: macos-14-xlarge
+  #   needs: output_detox_tests_to_run
+  #   env:
+  #     # Path to write secret key to. Also used by fastlane
+  #     APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
+  #     # Xcode project file name
+  #     IOS_PROJ_FILE: 'VAMobile.xcodeproj'
+  #     # Xcode scheme to build
+  #     IOS_SCHEME: 'VAMobileRelease'
 
-    strategy:
-      fail-fast: false
-      matrix:
-        testsuite: ${{fromJson(needs.output_detox_tests_to_run.outputs.output1)}}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       testsuite: ${{fromJson(needs.output_detox_tests_to_run.outputs.output1)}}
 
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ github.ref }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ github.ref }}
 
-      - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
-        working-directory: VAMobile/ios
-        run: |
-          echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
-          echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
+  #     - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
+  #       working-directory: VAMobile/ios
+  #       run: |
+  #         echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
+  #         echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
 
-      - name: Setup Xcode
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest-stable
+  #     - name: Setup Xcode
+  #       uses: maxim-lobanov/setup-xcode@v1
+  #       with:
+  #         xcode-version: latest-stable
 
-      - name: Setup node and restore yarn cache
-        uses: actions/setup-node@v3
-        with:
-          node-version-file: 'VAMobile/.nvmrc'
-          cache: 'yarn'
-          cache-dependency-path: './VAMobile/yarn.lock'
+  #     - name: Setup node and restore yarn cache
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version-file: 'VAMobile/.nvmrc'
+  #         cache: 'yarn'
+  #         cache-dependency-path: './VAMobile/yarn.lock'
 
-      - name: Install macOS dependencies
-        run: |
-          brew tap wix/brew
-          brew install applesimutils
-        env:
-          HOMEBREW_NO_AUTO_UPDATE: 1
-          HOMEBREW_NO_INSTALL_CLEANUP: 1
+  #     - name: Install macOS dependencies
+  #       run: |
+  #         brew tap wix/brew
+  #         brew install applesimutils
+  #       env:
+  #         HOMEBREW_NO_AUTO_UPDATE: 1
+  #         HOMEBREW_NO_INSTALL_CLEANUP: 1
 
-      - name: Install npm dependencies
-        run: yarn install --frozen-lockfile --non-interactive
+  #     - name: Install npm dependencies
+  #       run: yarn install --frozen-lockfile --non-interactive
 
-      - name: Set app environment variables
-        run: yarn env:staging
+  #     - name: Set app environment variables
+  #       run: yarn env:staging
 
-      - name: Install pods
-        working-directory: VAMobile/ios
-        run: pod install
+  #     - name: Install pods
+  #       working-directory: VAMobile/ios
+  #       run: pod install
   
-      - name: Install Ruby gems
-        working-directory: VAMobile/ios
-        run: bundle install
+  #     - name: Install Ruby gems
+  #       working-directory: VAMobile/ios
+  #       run: bundle install
 
-      - name: Bundle iOS app
-        run: yarn e2e:ios-build
+  #     - name: Bundle iOS app
+  #       run: yarn e2e:ios-build
 
-      - name: Run e2e tests for iOS with AF and Nav
-        run: yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
+  #     - name: Run e2e tests for iOS with AF and Nav
+  #       run: yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
       
-      - name: Upload e2e-junit
-        if: failure() || success()
-        uses: actions/upload-artifact@v3
-        with: 
-            name: ${{matrix.testsuite}}-e2e-junit
-            path: VAMobile/e2e/test_reports/e2e-junit.xml
+  #     - name: Upload e2e-junit
+  #       if: failure() || success()
+  #       uses: actions/upload-artifact@v3
+  #       with: 
+  #           name: ${{matrix.testsuite}}-e2e-junit
+  #           path: VAMobile/e2e/test_reports/e2e-junit.xml
 
-      - name: Upload artifacts on failure
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
-          path: VAMobile/artifacts
+  #     - name: Upload artifacts on failure
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
+  #         path: VAMobile/artifacts
 
-  e2e-ios:
-    if: always() && needs.output_detox_tests_to_run.outputs.output1 == '' && needs.output_detox_tests_to_run.outputs.output2 != ''
-    needs: [start_slack_thread, output_detox_tests_to_run]
-    runs-on: macos-14-xlarge
-    env:
-      # Path to write secret key to. Also used by fastlane
-      APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
-      # Xcode project file name
-      IOS_PROJ_FILE: 'VAMobile.xcodeproj'
-      # Xcode scheme to build
-      IOS_SCHEME: 'VAMobileRelease'
+  # e2e-ios:
+  #   if: always() && needs.output_detox_tests_to_run.outputs.output1 == '' && needs.output_detox_tests_to_run.outputs.output2 != ''
+  #   needs: [start_slack_thread, output_detox_tests_to_run]
+  #   runs-on: macos-14-xlarge
+  #   env:
+  #     # Path to write secret key to. Also used by fastlane
+  #     APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
+  #     # Xcode project file name
+  #     IOS_PROJ_FILE: 'VAMobile.xcodeproj'
+  #     # Xcode scheme to build
+  #     IOS_SCHEME: 'VAMobileRelease'
 
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ github.ref }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ github.ref }}
 
-      - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
-        working-directory: VAMobile/ios
-        run: |
-          echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
-          echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
+  #     - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
+  #       working-directory: VAMobile/ios
+  #       run: |
+  #         echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
+  #         echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
 
-      - name: Setup Xcode
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest-stable
+  #     - name: Setup Xcode
+  #       uses: maxim-lobanov/setup-xcode@v1
+  #       with:
+  #         xcode-version: latest-stable
 
-      - name: Setup node and restore yarn cache
-        uses: actions/setup-node@v3
-        with:
-          node-version-file: 'VAMobile/.nvmrc'
-          cache: 'yarn'
-          cache-dependency-path: './VAMobile/yarn.lock'
+  #     - name: Setup node and restore yarn cache
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version-file: 'VAMobile/.nvmrc'
+  #         cache: 'yarn'
+  #         cache-dependency-path: './VAMobile/yarn.lock'
 
-      - name: Install macOS dependencies
-        run: |
-          brew tap wix/brew
-          brew install applesimutils
-        env:
-          HOMEBREW_NO_AUTO_UPDATE: 1
-          HOMEBREW_NO_INSTALL_CLEANUP: 1
+  #     - name: Install macOS dependencies
+  #       run: |
+  #         brew tap wix/brew
+  #         brew install applesimutils
+  #       env:
+  #         HOMEBREW_NO_AUTO_UPDATE: 1
+  #         HOMEBREW_NO_INSTALL_CLEANUP: 1
 
-      - name: Install npm dependencies
-        run: yarn install --frozen-lockfile --non-interactive
+  #     - name: Install npm dependencies
+  #       run: yarn install --frozen-lockfile --non-interactive
 
-      - name: Set app environment variables
-        run: yarn env:staging
+  #     - name: Set app environment variables
+  #       run: yarn env:staging
 
-      - name: Install pods
-        working-directory: VAMobile/ios
-        run: pod install
+  #     - name: Install pods
+  #       working-directory: VAMobile/ios
+  #       run: pod install
   
-      - name: Install Ruby gems
-        working-directory: VAMobile/ios
-        run: bundle install
+  #     - name: Install Ruby gems
+  #       working-directory: VAMobile/ios
+  #       run: bundle install
 
-      - name: Bundle iOS app
-        run: yarn e2e:ios-build
+  #     - name: Bundle iOS app
+  #       run: yarn e2e:ios-build
 
-      - name: Run_e2e_tests_for_iOS
-        id: run_e2e_tests
-        run: yarn e2e:ios-test --take-screenshots failing --updateSnapshot
-        continue-on-error: true
+  #     - name: Run_e2e_tests_for_iOS
+  #       id: run_e2e_tests
+  #       run: yarn e2e:ios-test --take-screenshots failing --updateSnapshot
+  #       continue-on-error: true
 
-      - name: Upload e2e-junit
-        if: failure() || success()
-        uses: actions/upload-artifact@v3
-        with:
-          name: -e2e-junit
-          path: VAMobile/e2e/test_reports/e2e-junit.xml
+  #     - name: Upload e2e-junit
+  #       if: failure() || success()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: -e2e-junit
+  #         path: VAMobile/e2e/test_reports/e2e-junit.xml
 
-      - name: Inform Slack of Failure
-        id: post_failure
-        if: steps.run_e2e_tests.outcome == 'failure' && github.event_name == 'schedule'
-        run: |
-          ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
-            -H 'Content-type: application/json' \
-            --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Failed! Please check workflow for results: https://github.com/department-of-veterans-affairs/va-mobile-app/actions"}' \
-            https://slack.com/api/chat.postMessage|
-            jq -r '.ts')
-          echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
+  #     - name: Inform Slack of Failure
+  #       id: post_failure
+  #       if: steps.run_e2e_tests.outcome == 'failure' && github.event_name == 'schedule'
+  #       run: |
+  #         ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
+  #           -H 'Content-type: application/json' \
+  #           --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Failed! Please check workflow for results: https://github.com/department-of-veterans-affairs/va-mobile-app/actions"}' \
+  #           https://slack.com/api/chat.postMessage|
+  #           jq -r '.ts')
+  #         echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
 
-      - name: Inform Slack of success
-        id: post_success
-        if: steps.run_e2e_tests.outcome == 'success' && github.event_name == 'schedule'
-        run: |
-          ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
-            -H 'Content-type: application/json' \
-            --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Success! All E2E tests have passed"}' \
-            https://slack.com/api/chat.postMessage|
-            jq -r '.ts')
-          echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
+  #     - name: Inform Slack of success
+  #       id: post_success
+  #       if: steps.run_e2e_tests.outcome == 'success' && github.event_name == 'schedule'
+  #       run: |
+  #         ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
+  #           -H 'Content-type: application/json' \
+  #           --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Success! All E2E tests have passed"}' \
+  #           https://slack.com/api/chat.postMessage|
+  #           jq -r '.ts')
+  #         echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
 
-      - name: Upload artifacts on failure
-        if: steps.run_e2e_tests.outcome == 'failure'
-        uses: actions/upload-artifact@v3
-        with:
-          name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
-          path: VAMobile/artifacts
+  #     - name: Upload artifacts on failure
+  #       if: steps.run_e2e_tests.outcome == 'failure'
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
+  #         path: VAMobile/artifacts
 
-      - name: Fail workflow if needed(View e2e step for details)
-        if: steps.run_e2e_tests.outcome == 'failure'
-        run: exit 1
+  #     - name: Fail workflow if needed(View e2e step for details)
+  #       if: steps.run_e2e_tests.outcome == 'failure'
+  #       run: exit 1
 
-  matrix-send_test_results_to_testrail:
-    if: always() && github.event.inputs.run_testRail == 'true' && needs.output_detox_tests_to_run.outputs.output1 != ''
-    needs: [matrix-e2e-ios, output_detox_tests_to_run]
-    strategy:
-      fail-fast: false
-      max-parallel: 1
-      matrix:
-        testsuite: ${{ fromJSON(github.event.inputs.tests_to_run) }}     
-    name: Update testRail Results
-    uses: ./.github/workflows/update_testrail_results.yml
-    with: 
-      test_names: "${{matrix.testsuite}}"
-      testRail_name: ${{ inputs.testRail_name }}
-      test_specific_OS_needed: ${{ inputs.device_specific}}
-      test_OS_name: "iOS"
-    secrets: inherit
+  # matrix-send_test_results_to_testrail:
+  #   if: always() && github.event.inputs.run_testRail == 'true' && needs.output_detox_tests_to_run.outputs.output1 != ''
+  #   needs: [matrix-e2e-ios, output_detox_tests_to_run]
+  #   strategy:
+  #     fail-fast: false
+  #     max-parallel: 1
+  #     matrix:
+  #       testsuite: ${{ fromJSON(github.event.inputs.tests_to_run) }}     
+  #   name: Update testRail Results
+  #   uses: ./.github/workflows/update_testrail_results.yml
+  #   with: 
+  #     test_names: "${{matrix.testsuite}}"
+  #     testRail_name: ${{ inputs.testRail_name }}
+  #     test_specific_OS_needed: ${{ inputs.device_specific}}
+  #     test_OS_name: "iOS"
+  #   secrets: inherit
 
-  send_test_results_to_testrail:
-    if: always() && needs.output_detox_tests_to_run.outputs.output1 == '' && ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'skipped') || github.event.inputs.run_testRail == 'true')
-    needs: [e2e-ios, output_detox_tests_to_run]
-    name: Update testRail Results
-    uses: ./.github/workflows/update_testrail_results.yml
-    with: 
-      test_names: ""
-      testRail_name: ${{ inputs.testRail_name }}
-      test_specific_OS_needed: ${{ inputs.device_specific}}
-      test_OS_name: "iOS"
-    secrets: inherit
+  # send_test_results_to_testrail:
+  #   if: always() && needs.output_detox_tests_to_run.outputs.output1 == '' && ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'skipped') || github.event.inputs.run_testRail == 'true')
+  #   needs: [e2e-ios, output_detox_tests_to_run]
+  #   name: Update testRail Results
+  #   uses: ./.github/workflows/update_testrail_results.yml
+  #   with: 
+  #     test_names: ""
+  #     testRail_name: ${{ inputs.testRail_name }}
+  #     test_specific_OS_needed: ${{ inputs.device_specific}}
+  #     test_OS_name: "iOS"
+  #   secrets: inherit
