Update e2e_ios.yml

diff --git a/.github/workflows/e2e_ios.yml b/.github/workflows/e2e_ios.yml
--- a/.github/workflows/e2e_ios.yml
+++ b/.github/workflows/e2e_ios.yml
@@ -143,86 +143,86 @@ jobs:
         with:
           ref: ${{ github.ref }}
 
-      - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
-        working-directory: VAMobile/ios
-        run: |
-          echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
-          echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
+#       - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
+#         working-directory: VAMobile/ios
+#         run: |
+#           echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
+#           echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
 
-      - name: Setup Xcode
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest-stable
+#       - name: Setup Xcode
+#         uses: maxim-lobanov/setup-xcode@v1
+#         with:
+#           xcode-version: latest-stable
 
-      - name: Setup node and restore yarn cache
-        uses: actions/setup-node@v3
-        with:
-          node-version-file: 'VAMobile/.nvmrc'
-          cache: 'yarn'
-          cache-dependency-path: './VAMobile/yarn.lock'
+#       - name: Setup node and restore yarn cache
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version-file: 'VAMobile/.nvmrc'
+#           cache: 'yarn'
+#           cache-dependency-path: './VAMobile/yarn.lock'
 
-      - name: Install macOS dependencies
-        run: |
-          brew tap wix/brew
-          brew install applesimutils
-        env:
-          HOMEBREW_NO_AUTO_UPDATE: 1
-          HOMEBREW_NO_INSTALL_CLEANUP: 1
+#       - name: Install macOS dependencies
+#         run: |
+#           brew tap wix/brew
+#           brew install applesimutils
+#         env:
+#           HOMEBREW_NO_AUTO_UPDATE: 1
+#           HOMEBREW_NO_INSTALL_CLEANUP: 1
 
-      - name: Install npm dependencies
-        run: yarn install --frozen-lockfile --non-interactive
+#       - name: Install npm dependencies
+#         run: yarn install --frozen-lockfile --non-interactive
 
-      - name: Set app environment variables
-        run: yarn env:staging
+#       - name: Set app environment variables
+#         run: yarn env:staging
 
-      - name: Install pods
-        working-directory: VAMobile/ios
-        run: pod install
+#       - name: Install pods
+#         working-directory: VAMobile/ios
+#         run: pod install
   
-      - name: Install Ruby gems
-        working-directory: VAMobile/ios
-        run: bundle install
+#       - name: Install Ruby gems
+#         working-directory: VAMobile/ios
+#         run: bundle install
 
-      - name: Bundle iOS app
-        run: yarn e2e:ios-build
+#       - name: Bundle iOS app
+#         run: yarn e2e:ios-build
 
-      - name: Run e2e tests for iOS
-        id: run_e2e_tests
-        run: |
-          yarn e2e:ios-test /e2e/tests/${{matrix.testsuite}} --take-screenshots failing --updateSnapshot --headless
-# if [[ "${{needs.output_detox_tests_to_run.outputs.output2}}" == "" ]]; then
-#   yarn e2e:ios-test /e2e/tests/${{matrix.testsuite}} --take-screenshots failing --updateSnapshot --headless
-#   echo "NAV_AF_TEST_RUN=" >> "$GITHUB_OUTPUT"
-# else
-#   echo "NAV_AF_TEST_RUN=true" >> "$GITHUB_OUTPUT"
-#   yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
-# fi
-        continue-on-error: true
+#       - name: Run e2e tests for iOS
+#         id: run_e2e_tests
+#         run: |
+#           yarn e2e:ios-test /e2e/tests/${{matrix.testsuite}} --take-screenshots failing --updateSnapshot --headless
+# # if [[ "${{needs.output_detox_tests_to_run.outputs.output2}}" == "" ]]; then
+# #   yarn e2e:ios-test /e2e/tests/${{matrix.testsuite}} --take-screenshots failing --updateSnapshot --headless
+# #   echo "NAV_AF_TEST_RUN=" >> "$GITHUB_OUTPUT"
+# # else
+# #   echo "NAV_AF_TEST_RUN=true" >> "$GITHUB_OUTPUT"
+# #   yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
+# # fi
+#         continue-on-error: true
 
-      - name: Rerun e2e tests for iOS if failed
-        if: steps.run_e2e_tests.outcome == 'failure' && steps.run_e2e_tests.outputs.NAV_AF_TEST_RUN != ''
-        id: rerun_e2e_tests
-        run: |
-            yarn jest:clear;
-            yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
+#       - name: Rerun e2e tests for iOS if failed
+#         if: steps.run_e2e_tests.outcome == 'failure' && steps.run_e2e_tests.outputs.NAV_AF_TEST_RUN != ''
+#         id: rerun_e2e_tests
+#         run: |
+#             yarn jest:clear;
+#             yarn e2e:ios-test /e2e/tests/Navigation.e2e AvailabilityFramework.e2e ${{matrix.testsuite}}.e2e --take-screenshots failing --updateSnapshot --headless
 
-      - name: Upload e2e-junit
-        if: failure() || success()
-        uses: actions/upload-artifact@v4
-        with: 
-            name: ${{matrix.testsuite}}-e2e-junit
-            path: VAMobile/e2e/test_reports/e2e-junit.xml
+#       - name: Upload e2e-junit
+#         if: failure() || success()
+#         uses: actions/upload-artifact@v4
+#         with: 
+#             name: ${{matrix.testsuite}}-e2e-junit
+#             path: VAMobile/e2e/test_reports/e2e-junit.xml
 
-      - name: Upload artifacts on failure
-        if: failure() || steps.run_e2e_tests.outcome == 'failure'
-        uses: actions/upload-artifact@v4
-        with:
-          name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
-          path: VAMobile/artifacts
+#       - name: Upload artifacts on failure
+#         if: failure() || steps.run_e2e_tests.outcome == 'failure'
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: detox-artifacts-${{ runner.os }}-${{ github.run_id }}
+#           path: VAMobile/artifacts
 
-      - name: Fail workflow if needed(View e2e step for details)
-        if: steps.run_e2e_tests.outcome == 'failure'
-        run: exit 1
+#       - name: Fail workflow if needed(View e2e step for details)
+#         if: steps.run_e2e_tests.outcome == 'failure'
+#         run: exit 1
   
   output-slack-results:
     if: (!cancelled()) 
@@ -264,7 +264,7 @@ jobs:
       - name: Determine if ticket needs to be made
         id: find_if_ticket_already_exists
         run: |
-          tickets=$(gh issue list --state open --search "Bug - Detox - Fix Overnight Failures in:title")x
+          tickets=$(gh issue list --json --state open --search "Bug - Detox - Fix Overnight Failures in:title" | jq '.number')
           echo "$tickets"
           echo "TICKET_EXISTS=$tickets" >> "$GITHUB_OUTPUT"
         env:
@@ -274,7 +274,7 @@ jobs:
         id: failing_tests
         shell: bash
         run: |
-          failing_tests_list = $(grep -rl "<failure>")
+          failing_tests_list=$(grep -rl "<failure>")
           echo "FAILING_TEST=$failing_tests_list" >> "$GITHUB_OUTPUT"
       
       - name: Get new ticket body
