new logic

diff --git a/.github/workflows/pr-checks-for-qa-approvals.yml b/.github/workflows/pr-checks-for-qa-approvals.yml
--- a/.github/workflows/pr-checks-for-qa-approvals.yml
+++ b/.github/workflows/pr-checks-for-qa-approvals.yml
@@ -33,17 +33,23 @@ jobs:
         
         shell: bash
         run: |
-          
-          approvals=$(curl --request GET \
+          response=$(curl --silent --fail --request GET \
           --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100 \
           --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}' \
-          --header 'Content-Type: application/json' |
-          jq -c '[map(select(.state == "APPROVED")) | .[] .user.login]')
-
-          if [ -z "$approvals" ] || [ "$approvals" == "[]" ]; then
-            echo "No approvals found. Exiting."
-            exit 
+          --header 'Content-Type: application/json')
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch pull request reviews."
+            exit 1
           fi
+
+          approvals=$(echo "$response" | jq -r '[.[] | select(.state == "APPROVED") | .user.login] | @csv')
+
+          if [ -z "$approvals" ]; then
+            echo "No approvals found."
+          else
+            echo "Approved by: $approvals"
+          fi
+          
 
           echo "${{secrets.GH_ACTIONS_PAT}}" >> token.txt
           gh auth login --with-token < token.txt
