add debug step

diff --git a/.github/workflows/pr-checks-for-qa-approvals.yml b/.github/workflows/pr-checks-for-qa-approvals.yml
--- a/.github/workflows/pr-checks-for-qa-approvals.yml
+++ b/.github/workflows/pr-checks-for-qa-approvals.yml
@@ -33,14 +33,30 @@ jobs:
         
         shell: bash
         run: |
+          set -euo pipefail
+
+          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
+            echo "Error: GITHUB_TOKEN is not set."
+            exit 1
+          fi
+          echo "Repository: ${{ github.repository }}"
+          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
+
           response=$(curl --silent --fail --request GET \
           --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100 \
           --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}' \
-          --header 'Content-Type: application/json')
+          --header 'Content-Type: application/json') || {
+          echo "Failed to fetch pull request reviews. HTTP status code: $?"
+          exit 1
+          }
+
           if [ $? -ne 0 ]; then
             echo "Failed to fetch pull request reviews."
             exit 1
           fi
+
+          echo "Response: $response"
+
 
           approvals=$(echo "$response" | jq -r '[.[] | select(.state == "APPROVED") | .user.login] | @csv')
 
