Commenting out working things to test

diff --git a/.github/workflows/qa_required_approvals.yml b/.github/workflows/qa_required_approvals.yml
--- a/.github/workflows/qa_required_approvals.yml
+++ b/.github/workflows/qa_required_approvals.yml
@@ -24,53 +24,56 @@ jobs:
       - name: Check QA approval
         shell: bash
         run: |
-          if [[ "${{ github.event.pull_request.user.login }}" == "dependabot[bot]" ]]
-            then
-            echo "PR opened by Dependabot. Skipping QA approval check."
-            exit 0
-          fi
-          approvals=$(curl --request GET \
-          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100 \
-          --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}' \
-          --header 'Content-Type: application/json' |
-          jq -c '[map(select(.state == "APPROVED")) | .[] .user.login]')
-
+          echo "Debugging team members..."
           echo "${{secrets.GH_ACTIONS_PAT}}" >> token.txt
           gh auth login --with-token < token.txt
-
+          
           engineers=$(gh api orgs/department-of-veterans-affairs/teams/flagship-mobile-pr-reviewers/members | jq -c '[.[] .login]')
           qa_members=$(gh api orgs/department-of-veterans-affairs/teams/flagship-mobile-qa/members | jq -c '[.[] .login]')
 
           echo "Engineer team members: $engineers"
           echo "QA team members: $qa_members"
-
-          required_approval_count=$(gh api \
-          -H "Accept: application/vnd.github+json" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          /repos/department-of-veterans-affairs/va-mobile-app/branches/develop/protection |
-          jq -c '.required_pull_request_reviews.required_approving_review_count')
-
-          echo "Approvers: $approvals"  
-          echo "required approval count: $required_approval_count"
-
-          if [[ $(jq '. | length' <<< "$approvals") -ge $required_approval_count ]]
-            then
-              if [[ $(jq --argjson engineers "$engineers" '[.[] | select(. | IN($engineers[]))] | length' <<< "$approvals") -gt 0 ]]
-                then
-                echo 'This PR has at least one engineer approval. Now checking for QA approval...'
-                if [[ $(jq --argjson qa_members "$qa_members" '[.[] | select(. | IN($qa_members[]))] | length' <<< "$approvals") -gt 0 ]]
-                  then
-                  echo 'This PR has QA and engineer approval to merge'
-                  exit 0
-                else 
-                  echo 'This PR requires QA approval to merge'
-                  exit 1
-                fi
-              else
-                echo 'This PR requires Engineer approval before QA review'
-                exit 1
-              fi 
-          else
-            echo 'This PR requires two approvals, including one QA approval, before merging.'
-            exit 1
-          fi
+          
+          # The rest of the script is commented out for debugging purposes.
+          #
+          # if [[ "${{ github.event.pull_request.user.login }}" == "dependabot[bot]" ]]
+          #   then
+          #   echo "PR opened by Dependabot. Skipping QA approval check."
+          #   exit 0
+          # fi
+          # approvals=$(curl --request GET \
+          # --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100 \
+          # --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}' \
+          # --header 'Content-Type: application/json' |
+          # jq -c '[map(select(.state == "APPROVED")) | .[] .user.login]')
+          # 
+          # required_approval_count=$(gh api \
+          # -H "Accept: application/vnd.github+json" \
+          # -H "X-GitHub-Api-Version: 2022-11-28" \
+          # /repos/department-of-veterans-affairs/va-mobile-app/branches/develop/protection |
+          # jq -c '.required_pull_request_reviews.required_approving_review_count')
+          # 
+          # echo "Approvers: $approvals"  
+          # echo "required approval count: $required_approval_count"
+          # 
+          # if [[ $(jq '. | length' <<< "$approvals") -ge $required_approval_count ]]
+          #   then
+          #     if [[ $(jq --argjson engineers "$engineers" '[.[] | select(. | IN($engineers[]))] | length' <<< "$approvals") -gt 0 ]]
+          #       then
+          #       echo 'This PR has at least one engineer approval. Now checking for QA approval...'
+          #       if [[ $(jq --argjson qa_members "$qa_members" '[.[] | select(. | IN($qa_members[]))] | length' <<< "$approvals") -gt 0 ]]
+          #         then
+          #         echo 'This PR has QA and engineer approval to merge'
+          #         exit 0
+          #       else 
+          #         echo 'This PR requires QA approval to merge'
+          #         exit 1
+          #       fi
+          #     else
+          #       echo 'This PR requires Engineer approval before QA review'
+          #       exit 1
+          #     fi 
+          # else
+          #   echo 'This PR requires two approvals, including one QA approval, before merging.'
+          #   exit 1
+          # fi
