Testing some things. Hope nothing breaks

diff --git a/.github/workflows/release_branch_issue.yml b/.github/workflows/release_branch_issue.yml
--- a/.github/workflows/release_branch_issue.yml
+++ b/.github/workflows/release_branch_issue.yml
@@ -1,6 +1,7 @@
 name: "[Release] New Release Issue"
 
 on:
+  push:
   create:
 jobs:
   release_ticket:
@@ -63,23 +64,23 @@ jobs:
           gh issue edit $ISSUE_NUMBER --add-assignee $ASSIGNEES
         env:
           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-  create_testrail_milestone:
-    uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/create_testrail_milestone.yml@develop
-    needs: release_ticket
-    secrets:
-      TEST_RAIL_USER: ${{secrets.TEST_RAIL_USER}}
-      TEST_RAIL_KEY: ${{secrets.TEST_RAIL_KEY}}
-  start_testrail_run:
-    uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/start_test_rail_run.yml@develop
-    needs: [release_ticket, create_testrail_milestone]
-    with:
-      version: ${{ needs.release_ticket.outputs.versionNumber }}
-      releaseDate: ${{ needs.release_ticket.outputs.releaseDate }}
-      ticketNumber: ${{ needs.release_ticket.outputs.ticketNumber }}
-      milestoneId: ${{ needs.create_testrail_milestone.outputs.milestoneId }}
-    secrets:
-      TEST_RAIL_USER: ${{secrets.TEST_RAIL_USER}}
-      TEST_RAIL_KEY: ${{secrets.TEST_RAIL_KEY}}
+  # create_testrail_milestone:
+  #   uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/create_testrail_milestone.yml@develop
+  #   needs: release_ticket
+  #   secrets:
+  #     TEST_RAIL_USER: ${{secrets.TEST_RAIL_USER}}
+  #     TEST_RAIL_KEY: ${{secrets.TEST_RAIL_KEY}}
+  # start_testrail_run:
+  #   uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/start_test_rail_run.yml@develop
+  #   needs: [release_ticket, create_testrail_milestone]
+  #   with:
+  #     version: ${{ needs.release_ticket.outputs.versionNumber }}
+  #     releaseDate: ${{ needs.release_ticket.outputs.releaseDate }}
+  #     ticketNumber: ${{ needs.release_ticket.outputs.ticketNumber }}
+  #     milestoneId: ${{ needs.create_testrail_milestone.outputs.milestoneId }}
+  #   secrets:
+  #     TEST_RAIL_USER: ${{secrets.TEST_RAIL_USER}}
+  #     TEST_RAIL_KEY: ${{secrets.TEST_RAIL_KEY}}
   # NOTE: Commenting out until we fix issue # 6354
   # update_ticket:
   #   runs-on: ubuntu-latest
@@ -103,116 +104,116 @@ jobs:
   #         gh issue edit $TICKET_NUM -b $NEW_BODY
   #       env:
   #         GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-  close_milestone:
-    runs-on: ubuntu-latest
-    needs: [release_ticket]
-    steps:
-      - name: Generate token
-        id: generate_token
-        uses: actions/create-github-app-token@v1
-        with:
-          app-id: ${{ secrets.FLAGSHIP_MOBILE_APP_ID }}
-          private-key: ${{ secrets.FLAGSHIP_MOBILE_APP_PRIVATE_KEY }}
-      - uses: actions/checkout@v3
-        with:
-          token: ${{ steps.generate_token.outputs.token }}
-      - run: |
-          VERSION_NUMBER=${{ needs.release_ticket.outputs.versionNumber }}
-          TICKET_NUM=${{ needs.release_ticket.outputs.ticketNumber }}
-          MILESTONE_ID=$(gh api "repos/${{ github.repository }}/milestones" --jq '.[] | select(.title == "'"$VERSION_NUMBER"'") | .number')
-          echo Ticket Number: $TICKET_NUM
-          echo Version Numbver: $VERSION_NUMBER
-          echo Milestone ID: $MILESTONE_ID
-          gh api \
-            --method PATCH \
-            "repos/${{ github.repository }}/milestones/$MILESTONE_ID" \
-            -F state=closed
-        env:
-          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-  start_slack_thread:
-    if: ${{ success() || failure() }}
-    name: Start Slack thread
-    needs: release_ticket
-    uses: ./.github/workflows/start_slack_thread.yml
-    secrets: inherit
-    with:
-      channel_name: va-mobile-app
-      message: "*Release ${{ needs.release_ticket.outputs.versionNumber }} Coordination :thread:"
-  release_coordination:
-    name: release coordination
-    if: ${{ success() }}
-    needs: [start_slack_thread, release_ticket]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Map GitHub usernames to Slack IDs
-        id: map_slack_ids
-        run: |
-          declare -A GITHUB_TO_SLACK_MAP
-          GITHUB_TO_SLACK_MAP["rtwell"]="UEY4D750B"
-          GITHUB_TO_SLACK_MAP["becca"]="U08AWC7DQA2"
-          # Example: Convert mapping to environment variables
-          for key in "${!GITHUB_TO_SLACK_MAP[@]}"; do
-            echo "${key}=${GITHUB_TO_SLACK_MAP[$key]}" >> $GITHUB_ENV
-          done
-      - name: Notify Slack for release coordination
-        env:
-          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
-          SLACK_rtwell: $rtwell
-          SLACK_becca: $becca
-        run: |
-          SLACK_MESSAGE=$(cat <<EOF
-          {
-            "channel": "va-mobile-app",
-            "text": "*Release Ticket #:* <https://github.com/department-of-veterans-affairs/va-mobile-app/issues/${{ needs.release_ticket.outputs.ticketNumber }}|${{ needs.release_ticket.outputs.ticketNumber }}>\n\
-          *Release Report:* Github Report Link to be provided\n\
-          *Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n\
-          *Approval Timing:*\n\
-          - *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n\
-          - *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n\
-          - *Release Manager Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n\
-          - *Tickets Tagged Appropriately:* ${{ needs.release_ticket.outputs.qaDueDate }}\n\n\
-          *Contacts:*\n\
-            - *VA PO for awareness:* CC: <@${SLACK_rtwell}>\n\
-            - *Release coordination:* <@${SLACK_becca}>",
-            "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}",
-            "unfurl_links": false,
-            "unfurl_media": false
-          }
-          EOF
-          )
-          echo "$SLACK_MESSAGE" | envsubst | curl -X POST \
-               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
-               -H 'Content-type: application/json' \
-               -d @- \
-               https://slack.com/api/chat.postMessage
-  approval:
-    name: Run release approval
-    runs-on: ubuntu-latest
-    needs: release_ticket
-    environment:
-      name: release
-    steps:
-      - name: Generate token
-        id: generate_token
-        uses: actions/create-github-app-token@v1
-        with:
-          app-id: ${{ secrets.FLAGSHIP_MOBILE_APP_ID }}
-          private-key: ${{ secrets.FLAGSHIP_MOBILE_APP_PRIVATE_KEY }}
-      - name: "Checkout repo"
-        uses: actions/checkout@v3
-        with:
-          token: ${{ steps.generate_token.outputs.token }}
-      - name: get_approver
-        id: approver-id
-        run: |
-          APPROVER=$( gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals | jq '.[] | select(.state == "approved") | select(.user.login | contains("[bot]") | not) | .user.login')
-          APPROVER_NAME=$(echo "$APPROVER" | sed 's/"//g')
-          echo "approver=${APPROVER}" >> "$GITHUB_OUTPUT"
-          echo "approver_name=${APPROVER_NAME}" >> "$GITHUB_OUTPUT"
-          gh issue comment ${{ needs.release_ticket.outputs.ticketNumber }} -b "approving version ${{ needs.release_ticket.outputs.versionNumber }} 
-          Approved by: @$APPROVER_NAME"
-        env:
-          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-  run_approval_workflow:
-    uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/run_approval.yml@chore.12210.slash.command.update
-    secrets: inherit
+  # close_milestone:
+  #   runs-on: ubuntu-latest
+  #   needs: [release_ticket]
+  #   steps:
+  #     - name: Generate token
+  #       id: generate_token
+  #       uses: actions/create-github-app-token@v1
+  #       with:
+  #         app-id: ${{ secrets.FLAGSHIP_MOBILE_APP_ID }}
+  #         private-key: ${{ secrets.FLAGSHIP_MOBILE_APP_PRIVATE_KEY }}
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ steps.generate_token.outputs.token }}
+  #     - run: |
+  #         VERSION_NUMBER=${{ needs.release_ticket.outputs.versionNumber }}
+  #         TICKET_NUM=${{ needs.release_ticket.outputs.ticketNumber }}
+  #         MILESTONE_ID=$(gh api "repos/${{ github.repository }}/milestones" --jq '.[] | select(.title == "'"$VERSION_NUMBER"'") | .number')
+  #         echo Ticket Number: $TICKET_NUM
+  #         echo Version Numbver: $VERSION_NUMBER
+  #         echo Milestone ID: $MILESTONE_ID
+  #         gh api \
+  #           --method PATCH \
+  #           "repos/${{ github.repository }}/milestones/$MILESTONE_ID" \
+  #           -F state=closed
+  #       env:
+  #         GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
+  # start_slack_thread:
+  #   if: ${{ success() || failure() }}
+  #   name: Start Slack thread
+  #   needs: release_ticket
+  #   uses: ./.github/workflows/start_slack_thread.yml
+  #   secrets: inherit
+  #   with:
+  #     channel_name: va-mobile-app
+  #     message: "*Release ${{ needs.release_ticket.outputs.versionNumber }} Coordination :thread:"
+  # release_coordination:
+  #   name: release coordination
+  #   if: ${{ success() }}
+  #   needs: [start_slack_thread, release_ticket]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Map GitHub usernames to Slack IDs
+  #       id: map_slack_ids
+  #       run: |
+  #         declare -A GITHUB_TO_SLACK_MAP
+  #         GITHUB_TO_SLACK_MAP["rtwell"]="UEY4D750B"
+  #         GITHUB_TO_SLACK_MAP["becca"]="U08AWC7DQA2"
+  #         # Example: Convert mapping to environment variables
+  #         for key in "${!GITHUB_TO_SLACK_MAP[@]}"; do
+  #           echo "${key}=${GITHUB_TO_SLACK_MAP[$key]}" >> $GITHUB_ENV
+  #         done
+  #     - name: Notify Slack for release coordination
+  #       env:
+  #         SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
+  #         SLACK_rtwell: $rtwell
+  #         SLACK_becca: $becca
+  #       run: |
+  #         SLACK_MESSAGE=$(cat <<EOF
+  #         {
+  #           "channel": "va-mobile-app",
+  #           "text": "*Release Ticket #:* <https://github.com/department-of-veterans-affairs/va-mobile-app/issues/${{ needs.release_ticket.outputs.ticketNumber }}|${{ needs.release_ticket.outputs.ticketNumber }}>\n\
+  #         *Release Report:* Github Report Link to be provided\n\
+  #         *Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n\
+  #         *Approval Timing:*\n\
+  #         - *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n\
+  #         - *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n\
+  #         - *Release Manager Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n\
+  #         - *Tickets Tagged Appropriately:* ${{ needs.release_ticket.outputs.qaDueDate }}\n\n\
+  #         *Contacts:*\n\
+  #         # - *VA PO for awareness:* CC: <@${SLACK_rtwell}>\n\
+  #         # - *Release coordination:* <@${SLACK_becca}>",
+  #           "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}",
+  #           "unfurl_links": false,
+  #           "unfurl_media": false
+  #         }
+  #         EOF
+  #         )
+  #         echo "$SLACK_MESSAGE" | envsubst | curl -X POST \
+  #              -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
+  #              -H 'Content-type: application/json' \
+  #              -d @- \
+  #              https://slack.com/api/chat.postMessage
+      approval:
+        name: Run release approval
+        runs-on: ubuntu-latest
+        needs: release_ticket
+        environment:
+          name: release
+        steps:
+          - name: Generate token
+            id: generate_token
+            uses: actions/create-github-app-token@v1
+            with:
+              app-id: ${{ secrets.FLAGSHIP_MOBILE_APP_ID }}
+              private-key: ${{ secrets.FLAGSHIP_MOBILE_APP_PRIVATE_KEY }}
+          - name: "Checkout repo"
+            uses: actions/checkout@v3
+            with:
+              token: ${{ steps.generate_token.outputs.token }}
+          - name: get_approver
+            id: approver-id
+            run: |
+              APPROVER=$( gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals | jq '.[] | select(.state == "approved") | select(.user.login | contains("[bot]") | not) | .user.login')
+              APPROVER_NAME=$(echo "$APPROVER" | sed 's/"//g')
+              echo "approver=${APPROVER}" >> "$GITHUB_OUTPUT"
+              echo "approver_name=${APPROVER_NAME}" >> "$GITHUB_OUTPUT"
+              gh issue comment ${{ needs.release_ticket.outputs.ticketNumber }} -b "approving version ${{ needs.release_ticket.outputs.versionNumber }} 
+              Approved by: @$APPROVER_NAME"
+            env:
+              GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
+        run_approval_workflow:
+          uses: department-of-veterans-affairs/va-mobile-app/.github/workflows/run_approval.yml@chore.12210.slash.command.update
+          secrets: inherit
